import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations = {
  pt: {
    // Navbar
    'nav.home': 'Início',
    'nav.services': 'Serviços',
    'nav.iphone': 'iPhone',
    'nav.ipad': 'iPad',
    'nav.mac': 'Mac',
    'nav.watch': 'Watch',
    'nav.airpods': 'AirPods',
    'nav.otherServices': 'Outros Serviços',
    'nav.prices': 'Preços',
    'nav.faq': 'Dúvidas',
    'nav.appointment': 'Agendamento',
    'nav.contact': 'Contato',
    'nav.blog': 'Blog',
    'nav.quiz': 'Quiz',
    'nav.toggleMenu': 'Alternar Menu',
    
    // Language selector
    'language.portuguese': 'Português',
    'language.english': 'Inglês',
    
    // Theme
    'theme.light': 'Modo Claro',
    'theme.dark': 'Modo Escuro',
    'theme.toggle': 'Alternar Tema',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.tryAgain': 'Tentar Novamente',
    'common.learnMore': 'Saiba Mais',
    'common.contactUs': 'Entre em Contato',
    'common.whatsapp': 'WhatsApp',
    'common.email': 'E-mail',
    'common.phone': 'Telefone',
    'common.address': 'Endereço',
    'common.schedule': 'Horário de Funcionamento',
    'common.services': 'Serviços',
    'common.about': 'Sobre',
    'common.home': 'Início',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.send': 'Enviar',
    'common.submit': 'Enviar',
    'common.name': 'Nome',
    'common.message': 'Mensagem',
    'common.subject': 'Assunto',
    'common.device': 'Dispositivo',
    'common.problem': 'Problema',
    'common.description': 'Descrição',
    'common.date': 'Data',
    'common.time': 'Horário',
    'common.yes': 'Sim',
    'common.no': 'Não',
    
    // Hero Section
    'hero.welcome': 'Bem-vindo à Link TI',
    'hero.subtitle': 'Centro de Serviço Autorizado da Apple',
    'hero.description1': 'Aqui, trazemos a excelência Apple para Mato Grosso! Como centro de serviços autorizado, usamos apenas peças originais e contamos com técnicos certificados para cuidar do seu iPhone, iPad, Mac, Apple Watch e mais.',
    'hero.description2': 'Nosso compromisso? Reparos rápidos, atendimento acolhedor e dispositivos como novos.',
    'hero.servicesButton': 'Nossos Serviços',
    'hero.whatsappButton': 'Atendimento via WhatsApp',
    'hero.whatsappMessage': 'Olá, gostaria de informações sobre assistência técnica para dispositivos Apple.',
    
    // Services Section
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Confira nossa gama de serviços para seus dispositivos Apple',
    'services.iphone.title': 'iPhone',
    'services.iphone.description': 'Reparos de telas, baterias, câmeras e outros componentes para todos os modelos de iPhone.',
    'services.ipad.title': 'iPad',
    'services.ipad.description': 'Consertos para todos os modelos de iPad, incluindo telas, baterias e problemas de software.',
    'services.mac.title': 'Mac',
    'services.mac.description': 'Serviços para MacBook, iMac e Mac mini, desde upgrades até reparos de placa lógica.',
    'services.watch.title': 'Apple Watch',
    'services.watch.description': 'Reparo especializado para Apple Watch, incluindo telas, baterias e problemas de conectividade.',
    'services.airpods.title': 'AirPods',
    'services.airpods.description': 'Reparo especializado para AirPods, incluindo bateria, conectividade e limpeza profunda.',
    'services.learnMore': 'Saiba Mais',
    'services.viewDetails': 'Ver Detalhes',
    'services.cta.title': 'Precisa de assistência técnica?',
    'services.cta.description': 'Entre em contato conosco hoje mesmo para um orçamento personalizado.',
    'services.cta.contact': 'Entrar em Contato',
    'services.cta.viewPrices': 'Ver Preços',
    'services.description': 'Oferecemos serviços especializados para todos os dispositivos Apple com técnicos certificados e peças originais.',
    
    // About Section
    'about.title': 'Sobre Nossa Empresa',
    'about.subtitle': 'Excelência em serviços Apple há mais de 15 anos',
    'about.description1': 'Fundada em 2003, a Link TI é um centro de serviço autorizado Apple dedicado a fornecer reparos e manutenção de alta qualidade para todos os seus dispositivos Apple, desde 2010. Nossa equipe de técnicos certificados pela Apple tem anos de experiência e está comprometida em oferecer um serviço excepcional.',
    'about.highlight1': 'Primeiro Centro de Serviço Autorizado em MT, desde 2010.',
    'about.highlight2': 'Técnicos certificados pela Apple',
    'about.highlight3': 'Peças originais e garantia oficial',
    'about.highlight4': 'Laboratório com ferramentas homologadas pela Apple',
    'about.highlight5': 'Atendimento em garantia, Applecare e fora de garantia.',
    'about.highlight6': 'Diagnóstico preciso e transparente',
    'about.description2': 'Buscamos garantir que seus dispositivos Apple funcionem perfeitamente, proporcionando reparos rápidos e confiáveis com peças originais, sempre mantendo integridade e transparência em nossos diagnósticos e orçamentos.',
    'about.description3': 'Com mais de 65 mil reparos realizados com sucesso, somos a escolha confiável para cuidar dos seus dispositivos Apple.',
    'about.whatsappButton': 'Atendimento via WhatsApp',
    
    // CTA Section
    'cta.title': 'Precisando de reparo para seu dispositivo Apple?',
    'cta.description': 'Entre em contato conosco hoje mesmo. Nossos especialistas estão prontos para ajudar com qualquer problema no seu dispositivo.',
    'cta.contactButton': 'Entre em Contato',
    'cta.whatsappButton': 'Orçamento via WhatsApp',
    'cta.whatsappMessage': 'Olá, gostaria de solicitar um orçamento para reparo do meu dispositivo Apple.',
    
    // Blog Section
    'blog.title': 'Blog e Dicas',
    'blog.subtitle': 'Conteúdo exclusivo para você cuidar melhor dos seus dispositivos',
    'blog.readMore': 'Ler mais',
    'blog.viewAll': 'Ver Todos os Artigos',
    'blog.latestPosts': 'Últimas Publicações',
    'blog.categories': 'Categorias',
    'blog.tags': 'Tags',
    'blog.author': 'Autor',
    'blog.publishedOn': 'Publicado em',
    'blog.relatedPosts': 'Posts Relacionados',
    'blog.sharePost': 'Compartilhar Post',
    'blog.backToBlog': 'Voltar ao Blog',

    // Quiz Section
    'quiz.title': 'Quiz Interativo de iPhone',
    'quiz.subtitle': 'Teste seus conhecimentos sobre o uso do iPhone com este quiz interativo de 10 perguntas e ganhe descontos exclusivos em acessórios da Link TI!',
    'quiz.fastEasy': 'Rápido e Fácil',
    'quiz.fastEasyDesc': 'Apenas 10 perguntas sobre o uso básico do iPhone',
    'quiz.gainDiscounts': 'Ganhe Descontos',
    'quiz.gainDiscountsDesc': 'Até 15% de desconto em acessórios baseado na sua pontuação',
    'quiz.forEveryone': 'Para Todos',
    'quiz.forEveryoneDesc': 'Perguntas adequadas para usuários de todos os níveis',
    'quiz.discountSystem': 'Sistema de Descontos',
    'quiz.validInfo': 'Válido em qualquer acessório da Link TI - Apresente o print da tela de resultado em nossa recepção',
    'quiz.startQuiz': 'Começar Quiz 🚀',
    'quiz.questionOf': 'Pergunta {current} de {total}',
    'quiz.congratulations': 'Parabéns! Você é um expert em iPhone!',
    'quiz.veryGood': 'Muito Bom!',
    'quiz.greatWork': 'Ótimo Trabalho!',
    'quiz.goodPerformance': 'Bom Desempenho!',
    'quiz.almostThere': 'Quase lá!',
    'quiz.interesting': 'Interessante!',
    'quiz.keepStudying': 'Continue Estudando!',
    'quiz.youWon': 'Você ganhou {discount}% de desconto!',
    'quiz.validAccessories': 'Válido em qualquer acessório na Link TI',
    'quiz.printScreen': '📱 Dê um print nesta tela e apresente em nossa recepção',
    'quiz.dontGiveUp': 'Não desanime! Com mais prática você vai dominar o iPhone em pouco tempo.',
    'quiz.retakeQuiz': 'Refazer Quiz',
    'quiz.shareResult': 'Compartilhar Resultado',
    'quiz.shareText': 'Acabei de fazer o Quiz de iPhone da Link TI e acertei {score} de {total} perguntas ({percentage}%)! 📱✨',
    'quiz.copiedToClipboard': 'Resultado copiado para a área de transferência!',
    
    // Service Details
    'serviceDetail.whatsappMessage': 'Olá, gostaria de solicitar um orçamento para reparo.',
    'serviceDetail.ourServices': 'Nossos Serviços',
    'serviceDetail.completeSolutions': 'Soluções completas para seu dispositivo Apple',
    'serviceDetail.commonProblems': 'Problemas Comuns',
    'serviceDetail.frequentProblems': 'Os problemas mais frequentes que resolvemos',
    'serviceDetail.getQuote': 'Solicitar Orçamento',
    'serviceDetail.whatsappQuote': 'Orçamento via WhatsApp',
    'serviceDetail.requestRepair': 'Solicitar Reparo',
    'serviceDetail.needRepair': 'Precisando de reparo para seu dispositivo?',
    'serviceDetail.contactToday': 'Entre em contato conosco hoje mesmo para um orçamento sem compromisso. Nossos especialistas estão prontos para ajudar.',
    'serviceDetail.contactUs': 'Entre em Contato',
    
    // Contact Page
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Estamos aqui para ajudar com seus dispositivos Apple',
    'contact.form.title': 'Envie uma Mensagem',
    'contact.form.description': 'Precisa de assistência técnica para seu dispositivo Apple? Entre em contato conosco através de um dos nossos canais de atendimento.',
    'contact.form.success': 'Mensagem enviada com sucesso!',
    'contact.form.error': 'Erro ao enviar mensagem. Tente novamente.',
    'contact.info.title': 'Informações de Contato',
    'contact.hours.title': 'Horário de Funcionamento',
    'contact.hours.weekdays': 'Segunda a Sexta: 8h às 18h',
    'contact.hours.saturday': 'Sábado: 8h às 12h',
    'contact.hours.sunday': 'Domingo: Fechado',
    
    // FAQ Page
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Encontre respostas para as dúvidas mais comuns',
    'faq.seo.title': 'FAQ - Suporte Técnico Apple',
    'faq.seo.description': 'Encontre respostas para perguntas frequentes sobre serviços de reparo de dispositivos Apple.',
    'faq.searchPlaceholder': 'Buscar pergunta...',
    'faq.noResults': 'Nenhuma pergunta encontrada',
    'faq.stillHaveQuestions': 'Ainda tem dúvidas?',
    'faq.contactUs': 'Entre em contato conosco',
    'faq.errorLoading': 'Erro ao carregar perguntas frequentes. Tente novamente mais tarde.',
    'faq.tryAgain': 'Tentar novamente',
    'faq.categories.services': 'Serviços',
    'faq.categories.scheduling': 'Agendamento',
    'faq.categories.timeframe': 'Prazos',
    'faq.categories.warranty': 'Garantia',
    'faq.categories.procedures': 'Procedimentos',
    'faq.categories.general': 'Geral',
    'faq.default.services.question': 'Quais serviços oferecemos?',
    'faq.default.services.answer': 'Oferecemos serviços especializados de assistência técnica para produtos Apple, incluindo iPhone, iPad, MacBook e Apple Watch. Nossos serviços incluem substituição de tela, troca de bateria, reparo de placa lógica, recuperação de dados, entre outros.',
    'faq.default.scheduling.question': 'Como agendar um reparo?',
    'faq.default.scheduling.answer': 'Para agendar um reparo, você pode entrar em contato conosco via WhatsApp, telefone, ou através da nossa página de agendamento. Basta informar o modelo do dispositivo e o problema que está enfrentando, e nossa equipe entrará em contato para confirmar o horário e fornecer instruções.',
    'faq.default.timeframe.question': 'Quanto tempo leva para consertar meu dispositivo?',
    'faq.default.timeframe.answer': 'O tempo de reparo varia conforme o tipo de serviço. Reparos simples como troca de tela ou bateria podem ser realizados no mesmo dia, enquanto reparos mais complexos como problemas de placa lógica podem levar de 2 a 5 dias úteis, dependendo da disponibilidade de peças.',
    'faq.default.warranty.question': 'Os reparos têm garantia?',
    'faq.default.warranty.answer': 'Sim, todos os nossos serviços possuem garantia. Peças como baterias e telas têm garantia de 90 dias, enquanto reparos de placa lógica geralmente têm garantia de 30 dias. Os termos específicos são informados no momento da entrega do dispositivo reparado.',
    'faq.default.data.question': 'Perco meus dados durante o reparo?',
    'faq.default.data.answer': 'Fazemos o possível para preservar seus dados durante o reparo, mas sempre recomendamos fazer um backup completo do dispositivo antes de enviá-lo para manutenção. Em alguns casos específicos, como formatação do sistema ou substituição de placa lógica, a perda de dados é inevitável.',
    
    // Appointment Page
    'appointment.title': 'Agendamento',
    'appointment.subtitle': 'Agende seu atendimento de forma rápida e fácil',
    'appointment.seo.title': 'Agendamento - Assistência Técnica Apple',
    'appointment.seo.description': 'Agende seu atendimento para reparo de dispositivos Apple de forma rápida e fácil.',
    'appointment.introduction': 'Aqui você pode agendar seu atendimento diretamente com a Apple ou entrar em contato conosco via WhatsApp para um atendimento mais personalizado.',
    'appointment.buttonText': 'Agendar com a Apple',
    'appointment.whatsappMessage': 'Olá, gostaria de agendar um atendimento para meu dispositivo Apple.',
    'appointment.whatsappButton': 'Agendar via WhatsApp',
    'appointment.prepareSection.title': 'Prepare seu Dispositivo',
    'appointment.prepareSection.cards.backup.title': 'Fazer Backup',
    'appointment.prepareSection.cards.backup.description': 'Saiba como fazer backup dos seus dados antes do reparo.',
    'appointment.prepareSection.cards.prepare.title': 'Preparar para Reparo',
    'appointment.prepareSection.cards.prepare.description': 'Passos importantes para preparar seu dispositivo.',
    'appointment.prepareSection.cards.erase.title': 'Apagar Dados',
    'appointment.prepareSection.cards.erase.description': 'Como apagar dados com segurança antes do reparo.',
    'appointment.viewGuide': 'Ver Guia',
    'appointment.checklist.title': 'Lista de Verificação',
    'appointment.checklist.items.backup': 'Fazer backup completo dos dados',
    'appointment.checklist.items.findMy': 'Desativar "Buscar Meu iPhone/iPad"',
    'appointment.checklist.items.accessories': 'Remover capas e acessórios',
    'appointment.checklist.items.case': 'Trazer caixa original (se disponível)',
    'appointment.checklist.items.passwords': 'Anotar senhas importantes',
    'appointment.form.title': 'Agendar Atendimento',
    'appointment.form.success': 'Agendamento realizado com sucesso!',
    'appointment.form.error': 'Erro ao agendar. Tente novamente.',
    'appointment.selectDate': 'Selecione a data',
    'appointment.selectTime': 'Selecione o horário',
    'appointment.availableTimes': 'Horários disponíveis',
    'appointment.noAvailableTimes': 'Não há horários disponíveis para esta data',
    
    // Prices Page
    'prices.title': 'Tabela de Preços',
    'prices.subtitle': 'Valores transparentes para todos os nossos serviços',
    'prices.filterByDevice': 'Filtrar por dispositivo',
    'prices.allDevices': 'Todos os dispositivos',
    'prices.service': 'Serviço',
    'prices.price': 'Preço',
    'prices.warranty': 'Garantia',
    'prices.estimate': 'Orçamento',
    'prices.contactForQuote': 'Entre em contato para orçamento',
    'prices.note': 'Os preços podem variar dependendo do modelo e da complexidade do reparo.',
    'prices.searchPlaceholder': 'Buscar serviço...',
    'prices.dataNotSynced': 'Dados não sincronizados com Google Sheets.',
    
    // iPhone Service Page
    'iphone.title': 'Reparo de iPhone',
    'iphone.subtitle': 'Serviços especializados para todos os modelos de iPhone',
    'iphone.description': 'Oferecemos serviços completos de reparo para todos os modelos de iPhone, desde o iPhone SE até os modelos mais recentes. Nossos técnicos certificados utilizam peças originais Apple para garantir que seu dispositivo volte a funcionar como novo.',
    'iphone.features.screenReplacement.title': 'Substituição de Tela',
    'iphone.features.screenReplacement.description': 'Substituição de telas quebradas ou com defeito utilizando peças originais Apple para manter a qualidade e funcionalidade original.',
    'iphone.features.batteryReplacement.title': 'Troca de Bateria',
    'iphone.features.batteryReplacement.description': 'Substituição de baterias desgastadas que não mantêm mais a carga, utilizando baterias originais para máxima duração.',
    'iphone.features.cameraRepair.title': 'Reparo de Câmeras',
    'iphone.features.cameraRepair.description': 'Conserto de câmeras com defeito, problemas de foco ou que não ligam, restaurando a função fotográfica completa.',
    'iphone.features.audioProblems.title': 'Problemas de Áudio',
    'iphone.features.audioProblems.description': 'Reparo de alto-falantes, microfones e receptores de áudio para ligações e reprodução de mídia com qualidade.',
    'iphone.features.boardRepair.title': 'Reparo de Placa',
    'iphone.features.boardRepair.description': 'Diagnóstico e reparo de problemas na placa lógica do iPhone, incluindo problemas de conectividade e energia.',
    'iphone.features.softwareUpdate.title': 'Atualização de Software',
    'iphone.features.softwareUpdate.description': 'Resolução de problemas de software, atualizações de sistema e restauração de dispositivos travados ou com falhas.',
    'iphone.problems.brokenScreen': 'Tela quebrada ou rachada',
    'iphone.problems.batteryIssues': 'Bateria não carrega ou dura pouco',
    'iphone.problems.wontTurnOn': 'iPhone não liga ou reinicia sozinho',
    'iphone.problems.connectivity': 'Problemas de conectividade Wi-Fi ou celular',
    'iphone.problems.camera': 'Câmera não funciona ou está com qualidade reduzida',
    'iphone.problems.buttons': 'Botões físicos não respondem',
    'iphone.problems.charging': 'iPhone não carrega ou não reconhece o carregador',
    'iphone.problems.audio': 'Alto-falantes ou microfone com defeito',
    'iphone.whatsappMessage': 'Olá, gostaria de solicitar um orçamento para reparo do meu iPhone.',

    // iPad Service Page
    'ipad.title': 'Reparo de iPad',
    'ipad.subtitle': 'Serviços especializados para toda linha de iPad',
    'ipad.description': 'Nosso centro de serviço oferece reparos completos para todos os modelos de iPad, incluindo iPad Pro, iPad Air, iPad mini e iPad tradicional. Utilizamos peças originais e técnicos certificados para garantir reparos de alta qualidade.',
    'ipad.features.screenReplacement.title': 'Substituição de Tela',
    'ipad.features.screenReplacement.description': 'Reparo de telas quebradas, rachadas ou com problemas de touch usando peças originais para todos os modelos de iPad.',
    'ipad.features.batteryReplacement.title': 'Troca de Bateria',
    'ipad.features.batteryReplacement.description': 'Substituição de baterias desgastadas ou com problemas de carga, restaurando a autonomia original do seu iPad.',
    'ipad.features.connectorRepair.title': 'Reparo de Conector',
    'ipad.features.connectorRepair.description': 'Conserto de conectores de carregamento danificados ou com mau contato, garantindo carregamento adequado.',
    'ipad.features.wifiProblems.title': 'Problemas de Wi-Fi',
    'ipad.features.wifiProblems.description': 'Diagnóstico e reparo de problemas de conectividade Wi-Fi e Bluetooth que afetam o desempenho do iPad.',
    'ipad.features.buttonRepair.title': 'Reparo de Botões',
    'ipad.features.buttonRepair.description': 'Conserto de botões físicos como Power, Home e controles de volume que não respondem corretamente.',
    'ipad.features.softwareProblems.title': 'Problemas de Software',
    'ipad.features.softwareProblems.description': 'Resolução de travamentos, lentidão e outros problemas de software através de diagnóstico especializado.',
    'ipad.problems.brokenScreen': 'Tela quebrada ou com problemas de toque',
    'ipad.problems.wontTurnOn': 'iPad não liga ou desliga sozinho',
    'ipad.problems.batteryDrain': 'Bateria descarrega rapidamente',
    'ipad.problems.charging': 'Problemas de carregamento',
    'ipad.problems.connectivity': 'Wi-Fi ou Bluetooth não funcionam corretamente',
    'ipad.problems.freezing': 'iPad travando ou com desempenho lento',
    'ipad.problems.buttons': 'Botões físicos não respondem',
    'ipad.problems.camera': 'Problemas com câmeras frontal ou traseira',
    'ipad.whatsappMessage': 'Olá, gostaria de solicitar um orçamento para reparo do meu iPad.',

    // Mac Service Page
    'mac.title': 'Reparo de Mac',
    'mac.subtitle': 'Serviços especializados para MacBook, iMac e Mac mini',
    'mac.description': 'Oferecemos serviços completos de reparo e manutenção para toda linha Mac, incluindo MacBook Pro, MacBook Air, iMac e Mac mini. Nossos técnicos são especializados em diagnosticar e resolver problemas complexos de hardware e software.',
    'mac.features.screenRepair.title': 'Reparo de Tela',
    'mac.features.screenRepair.description': 'Substituição de telas quebradas ou com problemas de exibição para MacBook Pro, MacBook Air e iMac.',
    'mac.features.ssdUpgrade.title': 'Upgrade de SSD/HD',
    'mac.features.ssdUpgrade.description': 'Aumento de capacidade de armazenamento e melhoria de desempenho com instalação de SSDs mais rápidos.',
    'mac.features.ramUpgrade.title': 'Upgrade de RAM',
    'mac.features.ramUpgrade.description': 'Aumento da memória RAM para melhor desempenho em multitarefas e aplicativos exigentes.',
    'mac.features.logicBoardRepair.title': 'Reparo de Placa Lógica',
    'mac.features.logicBoardRepair.description': 'Diagnóstico e reparo de problemas complexos na placa lógica que afetam o funcionamento do Mac.',
    'mac.features.batteryReplacement.title': 'Troca de Bateria',
    'mac.features.batteryReplacement.description': 'Substituição de baterias desgastadas em MacBooks, restaurando a autonomia original do dispositivo.',
    'mac.features.keyboardRepair.title': 'Reparo de Teclado',
    'mac.features.keyboardRepair.description': 'Conserto de teclados com teclas defeituosas, problemas de resposta ou danos por líquidos.',
    'mac.problems.wontTurnOn': 'Mac não liga ou desliga inesperadamente',
    'mac.problems.brokenScreen': 'Tela quebrada ou com problemas de exibição',
    'mac.problems.battery': 'Bateria não carrega ou dura pouco tempo',
    'mac.problems.slowPerformance': 'Lentidão e problemas de desempenho',
    'mac.problems.keyboardTrackpad': 'Problemas com teclado ou trackpad',
    'mac.problems.osErrors': 'Erros no sistema operacional',
    'mac.problems.strangeNoises': 'Ruídos estranhos (ventilador, disco rígido)',
    'mac.problems.connectivity': 'Problemas de conexão Wi-Fi ou Bluetooth',
    'mac.problems.liquidDamage': 'Danos causados por líquidos',
    'mac.whatsappMessage': 'Olá, gostaria de solicitar um orçamento para reparo do meu Mac.',

    // Apple Watch Service Page
    'watch.title': 'Reparo de Apple Watch',
    'watch.subtitle': 'Serviços especializados para todos os modelos de Apple Watch',
    'watch.description': 'Nosso centro autorizado oferece reparos completos para todos os modelos de Apple Watch, desde a Série 1 até os modelos mais recentes. Utilizamos peças originais e técnicos certificados para garantir o funcionamento perfeito do seu dispositivo.',
    'watch.features.screenReplacement.title': 'Substituição de Tela',
    'watch.features.screenReplacement.description': 'Reparo de telas quebradas ou arranhadas para todos os modelos de Apple Watch, restaurando a aparência original.',
    'watch.features.batteryReplacement.title': 'Troca de Bateria',
    'watch.features.batteryReplacement.description': 'Substituição de baterias desgastadas que não mantêm mais a carga, restaurando a autonomia do seu Apple Watch.',
    'watch.features.buttonRepair.title': 'Reparo de Botões',
    'watch.features.buttonRepair.description': 'Conserto de coroa digital e botões laterais que não respondem corretamente ao toque ou pressão.',
    'watch.features.sensorProblems.title': 'Problemas de Sensores',
    'watch.features.sensorProblems.description': 'Diagnóstico e reparo de sensores de frequência cardíaca, acelerômetro e outros sensores específicos.',
    'watch.features.sealReplacement.title': 'Substituição de Vedações',
    'watch.features.sealReplacement.description': 'Restauração da resistência à água com a substituição de vedações e borrachas de proteção.',
    'watch.features.softwareUpdate.title': 'Atualização de Software',
    'watch.features.softwareUpdate.description': 'Resolução de problemas de software, restauração do sistema e correção de bugs específicos.',
    'watch.problems.brokenScreen': 'Tela quebrada ou arranhada',
    'watch.problems.batteryDrain': 'Bateria descarrega rapidamente',
    'watch.problems.wontTurnOn': 'Apple Watch não liga ou não carrega',
    'watch.problems.buttons': 'Botões não respondem corretamente',
    'watch.problems.sensors': 'Sensores de saúde não funcionam adequadamente',
    'watch.problems.pairing': 'Problemas de pareamento com iPhone',
    'watch.problems.waterResistance': 'Perda da resistência à água',
    'watch.problems.crashes': 'Travamentos ou reinicializações inesperadas',
    'watch.whatsappMessage': 'Olá, gostaria de solicitar um orçamento para reparo do meu Apple Watch.',

    // AirPods Service Page
    'airpods.title': 'Reparo de AirPods',
    'airpods.subtitle': 'Serviços especializados para todos os modelos de AirPods',
    'airpods.description': 'Oferecemos serviços completos de reparo para todos os modelos de AirPods, incluindo AirPods Pro, AirPods Max e modelos mais antigos. Nossos técnicos especializados resolvem problemas de conectividade, áudio e bateria.',
    'airpods.features.batteryReplacement.title': 'Substituição de Bateria',
    'airpods.features.batteryReplacement.description': 'Troca de baterias desgastadas dos AirPods e do estojo de carregamento para restaurar a autonomia original.',
    'airpods.features.connectivityRepair.title': 'Reparo de Conectividade',
    'airpods.features.connectivityRepair.description': 'Correção de problemas de pareamento, conexão instável e falhas na conectividade Bluetooth.',
    'airpods.features.deepCleaning.title': 'Limpeza Profunda',
    'airpods.features.deepCleaning.description': 'Limpeza especializada para remover cera, sujeira e detritos que afetam a qualidade do áudio.',
    'airpods.features.audioCalibration.title': 'Calibração de Áudio',
    'airpods.features.audioCalibration.description': 'Ajuste e calibração do áudio para restaurar a qualidade sonora original dos AirPods.',
    'airpods.features.chargingCaseRepair.title': 'Reparo do Estojo',
    'airpods.features.chargingCaseRepair.description': 'Conserto de problemas no estojo de carregamento, incluindo porta de carregamento e indicadores LED.',
    'airpods.features.microphoneProblems.title': 'Problemas de Microfone',
    'airpods.features.microphoneProblems.description': 'Reparo de microfones com defeito que afetam chamadas e comandos de voz como Siri.',
    'airpods.problems.batteryIssues': 'Bateria descarrega rapidamente',
    'airpods.problems.pairing': 'AirPods não pareiam com dispositivos',
    'airpods.problems.audioQuality': 'Qualidade de áudio reduzida ou distorcida',
    'airpods.problems.caseNotCharging': 'Estojo não carrega os AirPods',
    'airpods.problems.microphone': 'Problemas de microfone em chamadas',
    'airpods.problems.notRecognized': 'AirPods não são reconhecidos pelo iPhone',
    'airpods.problems.audioNoise': 'Ruídos ou chiados durante reprodução',
    'airpods.problems.noiseCancellation': 'Problemas com cancelamento de ruído (AirPods Pro)',
    'airpods.whatsappMessage': 'Olá, gostaria de solicitar um orçamento para reparo de AirPods.',

    // Other Services Page
    'otherServices.title': 'Outros Serviços',
    'otherServices.subtitle': 'Serviços especializados para todos os seus dispositivos Apple',
    'otherServices.description': 'Além dos reparos tradicionais, oferecemos uma gama completa de serviços para manter seus dispositivos Apple funcionando perfeitamente.',
    'otherServices.beats.title': 'Beats',
    'otherServices.beats.description': 'Serviços completos para fones Beats, incluindo reparo de drivers, substituição de almofadas, problemas de cabo e manutenção geral.',
    'otherServices.beats.driverRepair': 'Reparo de drivers',
    'otherServices.beats.padReplacement': 'Substituição de almofadas',
    'otherServices.beats.cableRepair': 'Reparo de cabos',
    'otherServices.beats.preventiveMaintenance': 'Manutenção preventiva',
    'otherServices.beats.whatsappMessage': 'Olá, gostaria de informações sobre reparo de fones Beats.',
    'otherServices.beats.getQuote': 'Orçamento para Beats',
    'otherServices.rental.title': 'Locação',
    'otherServices.rental.description': 'Aluguel de smartphones temporários para uso durante o período de reparo do seu dispositivo, mantendo você sempre conectado.',
    'otherServices.rental.temporaryIphone': 'iPhone temporário',
    'otherServices.rental.dailyWeekly': 'Locação diária ou semanal',
    'otherServices.rental.basicPremium': 'Modelos básicos e premium',
    'otherServices.rental.setupIncluded': 'Setup incluído',
    'otherServices.rental.whatsappMessage': 'Olá, gostaria de informações sobre locação de smartphones.',
    'otherServices.rental.requestRental': 'Solicitar Locação',
    'otherServices.recovery.title': 'Recuperação',
    'otherServices.recovery.description': 'Serviços especializados em recuperação de dados perdidos, backup completo e restauração de informações importantes dos seus dispositivos.',
    'otherServices.recovery.photosVideos': 'Recuperação de fotos e vídeos',
    'otherServices.recovery.fullBackup': 'Backup completo',
    'otherServices.recovery.contactRestore': 'Restauração de contatos',
    'otherServices.recovery.dataMigration': 'Migração de dados',
    'otherServices.recovery.whatsappMessage': 'Olá, gostaria de informações sobre recuperação de dados.',
    'otherServices.recovery.recoverData': 'Recuperar Dados',
    'otherServices.priceTable.title': 'Tabela de Preços - Serviços Especiais',
    'otherServices.priceTable.description': 'Confira nossa tabela de preços para serviços especializados. Valores sujeitos a alteração mediante avaliação.',
    'otherServices.categories.physicalCleaning': 'Limpeza Física',
    'otherServices.categories.backupRestore': 'Backup e Restauração',
    'otherServices.categories.smartphoneRental': 'Locação de Smartphones',
    'otherServices.categories.diagnosticConsulting': 'Diagnóstico e Consultoria',
    'otherServices.cleaning.iphone': 'Limpeza interna e externa completa',
    'otherServices.cleaning.ipad': 'Limpeza interna e externa completa',
    'otherServices.cleaning.macbook': 'Limpeza interna e externa, teclado e tela',
    'otherServices.cleaning.imac': 'Limpeza interna e externa completa',
    'otherServices.cleaning.applewatch': 'Limpeza externa e pulseira',
    'otherServices.backup.iphoneipad': 'Backup completo e restauração de dados',
    'otherServices.backup.mac': 'Time Machine ou backup personalizado',
    'otherServices.backup.dataRecovery': 'Recuperação de arquivos perdidos',
    'otherServices.rental.temporaryIphoneDaily': 'Locação de iPhone durante reparo do seu dispositivo',
    'otherServices.rental.basicIphone': 'Locação semanal de iPhone com funcionalidades básicas',
    'otherServices.rental.premiumIphone': 'Locação semanal de iPhone com todas as funcionalidades',
    'otherServices.diagnostic.complete': 'Análise detalhada do dispositivo',
    'otherServices.diagnostic.technicalConsulting': 'Orientação técnica especializada',
    'otherServices.diagnostic.initialSetup': 'Configuração inicial de novos dispositivos',
    'otherServices.table.device': 'Dispositivo/Serviço',
    'otherServices.table.price': 'Preço',
    'otherServices.table.description': 'Descrição',
    'otherServices.note': 'Todos os preços são estimativas e podem variar conforme a complexidade do reparo. Oferecemos orçamento gratuito e sem compromisso. Garantia de 90 dias para todos os serviços.',
    'otherServices.customService.title': 'Precisa de um serviço personalizado?',
    'otherServices.customService.description': 'Entre em contato conosco para serviços não listados ou orçamentos personalizados.',
    'otherServices.customService.whatsappMessage': 'Olá, gostaria de informações sobre serviços especializados.',

    // SOS Dados Page
    'sosData.badge': 'EMERGÊNCIA',
    'sosData.hero.title': 'SOS Dados',
    'sosData.hero.description': 'Perdeu dados importantes? Podemos ajudar você a recuperá-los!',
    'sosData.hero.button': 'Recuperar Meus Dados',
    'sosData.hero.diagnosisButton': 'Diagnóstico Gratuito',
    'sosData.hero.clients': 'Mais de 1000 clientes atendidos',
    'sosData.whatsappMessage': 'Olá, preciso de recuperação de dados de emergência para meu dispositivo.',
    'sosData.alert.message': '⚠️ Quanto mais rápido você entrar em contato, maiores as chances de recuperação - Não ligue o dispositivo!',
    'sosData.servicesSection.title': 'O Que Podemos Recuperar?',
    'sosData.servicesSection.description': 'Especializamos em recuperação de dados de diferentes tipos de dispositivos e mídias de armazenamento.',
    'sosData.services.hdd.title': 'HDs e SSDs',
    'sosData.services.hdd.description': 'Recuperação de danos mecânicos, corrupção lógica e falhas de sistema.',
    'sosData.services.mobile.title': 'Dispositivos Móveis',
    'sosData.services.mobile.description': 'iPhone, iPad e Android com danos físicos ou corrupção de sistema.',
    'sosData.services.computers.title': 'Computadores',
    'sosData.services.computers.description': 'Mac, PC, laptops com problemas de sistema ou falhas de hardware.',
    'sosData.services.servers.title': 'Servidores e RAID',
    'sosData.services.servers.description': 'Recuperação de dados críticos de servidores corporativos e sistemas RAID.',
    'sosData.urgency.critical': 'Crítico',
    'sosData.urgency.high': 'Alto',
    'sosData.urgency.medium': 'Médio',
    'sosData.processSection.title': 'Nosso Processo de Recuperação',
    'sosData.processSection.description': 'Um processo seguro e profissional para maximizar suas chances de recuperação.',
    'sosData.steps.contact.title': 'Contato de Emergência',
    'sosData.steps.contact.description': 'Entre em contato imediatamente e descreva o problema.',
    'sosData.steps.diagnosis.title': 'Diagnóstico Gratuito',
    'sosData.steps.diagnosis.description': 'Análise completa para avaliar as possibilidades de recuperação.',
    'sosData.steps.quote.title': 'Aprovação do Orçamento',
    'sosData.steps.quote.description': 'Apresentamos um orçamento detalhado sem surpresas.',
    'sosData.steps.recovery.title': 'Recuperação dos Dados',
    'sosData.steps.recovery.description': 'Utilizamos técnicas avançadas para recuperar seus arquivos.',
    'sosData.steps.delivery.title': 'Entrega Segura',
    'sosData.steps.delivery.description': 'Seus dados são devolvidos com segurança e confidencialidade.',
    'sosData.featuresSection.title': 'Por Que Escolher a Gente?',
    'sosData.features.security.title': 'Segurança Total',
    'sosData.features.security.description': 'Total confidencialidade e manuseio seguro dos seus dados.',
    'sosData.features.diagnosis.title': 'Diagnóstico Gratuito',
    'sosData.features.diagnosis.description': 'Avaliação completa sem custo e sem compromisso.',
    'sosData.features.successRate.title': '98% de Sucesso',
    'sosData.features.successRate.description': 'Alta taxa de sucesso na recuperação com tecnologia avançada.',
    'sosData.features.equipment.title': 'Equipamentos Avançados',
    'sosData.features.equipment.description': 'Sala limpa e tecnologia de ponta para casos complexos.',
    'sosData.cta.title': 'Cada Segundo Conta!',
    'sosData.cta.description': 'Quanto mais rápido você entrar em contato, maiores as chances de recuperação completa dos seus dados.',
    'sosData.cta.whatsapp': 'WhatsApp de Emergência',
    'sosData.cta.features.diagnosis': 'Diagnóstico Gratuito',
    'sosData.cta.features.noDataNoPayment': 'Sem Dados, Sem Pagamento',
    'sosData.cta.features.technology': 'Tecnologia Avançada',
    
    // Footer
    'footer.services': 'Serviços',
    'footer.company': 'Empresa',
    'footer.support': 'Suporte',
    'footer.followUs': 'Siga-nos',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Uso',
    'footer.cookies': 'Política de Cookies',
    'footer.warranty': 'Garantia',
    
    // Error Messages
    'error.pageNotFound': 'Página não encontrada',
    'error.goHome': 'Voltar ao início',
    'error.somethingWrong': 'Algo deu errado',
    'error.tryAgain': 'Tente novamente',
    
    // Course Pages
    'course.title': 'Curso de iPhone',
    'course.subtitle': 'Aprenda a usar seu iPhone como um profissional',
    'course.beginner': 'Iniciante',
    'course.intermediate': 'Intermediário',
    'course.advanced': 'Avançado',
    'course.contents': 'Conteúdos',
    'course.quiz': 'Quiz',
    'course.progress': 'Progresso',
    'course.completed': 'Concluído',
    'course.inProgress': 'Em andamento',
    'course.notStarted': 'Não iniciado'
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.iphone': 'iPhone',
    'nav.ipad': 'iPad',
    'nav.mac': 'Mac',
    'nav.watch': 'Watch',
    'nav.airpods': 'AirPods',
    'nav.otherServices': 'Other Services',
    'nav.prices': 'Prices',
    'nav.faq': 'FAQ',
    'nav.appointment': 'Appointment',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.quiz': 'Quiz',
    'nav.toggleMenu': 'Toggle Menu',
    
    // Language selector
    'language.portuguese': 'Portuguese',
    'language.english': 'English',
    
    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.toggle': 'Toggle Theme',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.tryAgain': 'Try Again',
    'common.learnMore': 'Learn More',
    'common.contactUs': 'Contact Us',
    'common.whatsapp': 'WhatsApp',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.schedule': 'Business Hours',
    'common.services': 'Services',
    'common.about': 'About',
    'common.home': 'Home',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.send': 'Send',
    'common.submit': 'Submit',
    'common.name': 'Name',
    'common.message': 'Message',
    'common.subject': 'Subject',
    'common.device': 'Device',
    'common.problem': 'Problem',
    'common.description': 'Description',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Hero Section
    'hero.welcome': 'Welcome to Link TI',
    'hero.subtitle': 'Apple Authorized Service Center',
    'hero.description1': 'Here, we bring Apple excellence to Mato Grosso! As an authorized service center, we use only original parts and have Apple-certified technicians to care for your iPhone, iPad, Mac, Apple Watch and more.',
    'hero.description2': 'Our commitment? Fast repairs, welcoming service and devices like new.',
    'hero.servicesButton': 'Our Services',
    'hero.whatsappButton': 'WhatsApp Support',
    'hero.whatsappMessage': 'Hello, I would like information about technical assistance for Apple devices.',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Check out our range of services for your Apple devices',
    'services.iphone.title': 'iPhone',
    'services.iphone.description': 'Screen, battery, camera and other component repairs for all iPhone models.',
    'services.ipad.title': 'iPad',
    'services.ipad.description': 'Repairs for all iPad models, including screens, batteries and software issues.',
    'services.mac.title': 'Mac',
    'services.mac.description': 'Services for MacBook, iMac and Mac mini, from upgrades to logic board repairs.',
    'services.watch.title': 'Apple Watch',
    'services.watch.description': 'Specialized Apple Watch repair, including screens, batteries and connectivity issues.',
    'services.airpods.title': 'AirPods',
    'services.airpods.description': 'Specialized AirPods repair, including battery, connectivity and deep cleaning.',
    'services.learnMore': 'Learn More',
    'services.viewDetails': 'View Details',
    'services.cta.title': 'Need technical assistance?',
    'services.cta.description': 'Contact us today for a personalized quote.',
    'services.cta.contact': 'Contact Us',
    'services.cta.viewPrices': 'View Prices',
    'services.description': 'We offer specialized services for all Apple devices with certified technicians and original parts.',
    
    // About Section
    'about.title': 'About Our Company',
    'about.subtitle': 'Excellence in Apple services for over 15 years',
    'about.description1': 'Founded in 2003, Link TI is an Apple authorized service center dedicated to providing high-quality repairs and maintenance for all your Apple devices since 2010. Our team of Apple-certified technicians has years of experience and is committed to providing exceptional service.',
    'about.highlight1': 'First Authorized Service Center in MT, since 2010.',
    'about.highlight2': 'Apple certified technicians',
    'about.highlight3': 'Original parts and official warranty',
    'about.highlight4': 'Laboratory with Apple-approved tools',
    'about.highlight5': 'In-warranty, AppleCare and out-of-warranty service.',
    'about.highlight6': 'Accurate and transparent diagnosis',
    'about.description2': 'We seek to ensure that your Apple devices work perfectly, providing fast and reliable repairs with original parts, always maintaining integrity and transparency in our diagnoses and quotes.',
    'about.description3': 'With over 65,000 successful repairs performed, we are the reliable choice to care for your Apple devices.',
    'about.whatsappButton': 'WhatsApp Support',
    
    // CTA Section
    'cta.title': 'Need repair for your Apple device?',
    'cta.description': 'Contact us today. Our specialists are ready to help with any problem on your device.',
    'cta.contactButton': 'Contact Us',
    'cta.whatsappButton': 'Quote via WhatsApp',
    'cta.whatsappMessage': 'Hello, I would like to request a quote for repairing my Apple device.',
    
    // Blog Section
    'blog.title': 'Blog & Tips',
    'blog.subtitle': 'Exclusive content to help you better care for your devices',
    'blog.readMore': 'Read more',
    'blog.viewAll': 'View All Articles',
    'blog.latestPosts': 'Latest Posts',
    'blog.categories': 'Categories',
    'blog.tags': 'Tags',
    'blog.author': 'Author',
    'blog.publishedOn': 'Published on',
    'blog.relatedPosts': 'Related Posts',
    'blog.sharePost': 'Share Post',
    'blog.backToBlog': 'Back to Blog',

    // Quiz Section
    'quiz.title': 'Interactive iPhone Quiz',
    'quiz.subtitle': 'Test your knowledge about iPhone usage with this interactive 10-question quiz and earn exclusive discounts on Link TI accessories!',
    'quiz.fastEasy': 'Fast and Easy',
    'quiz.fastEasyDesc': 'Just 10 questions about basic iPhone usage',
    'quiz.gainDiscounts': 'Earn Discounts',
    'quiz.gainDiscountsDesc': 'Up to 15% discount on accessories based on your score',
    'quiz.forEveryone': 'For Everyone',
    'quiz.forEveryoneDesc': 'Questions suitable for users of all levels',
    'quiz.discountSystem': '🎁 Discount System',
    'quiz.validInfo': 'Valid on any Link TI accessory - Present a screenshot of the result screen at our reception',
    'quiz.startQuiz': 'Start Quiz 🚀',
    'quiz.questionOf': 'Question {current} of {total}',
    'quiz.congratulations': 'Congratulations! You are an iPhone expert!',
    'quiz.veryGood': 'Very Good!',
    'quiz.greatWork': 'Great Work!',
    'quiz.goodPerformance': 'Good Performance!',
    'quiz.almostThere': 'Almost There!',
    'quiz.interesting': 'Interesting!',
    'quiz.keepStudying': 'Keep Studying!',
    'quiz.youWon': 'You earned {discount}% discount!',
    'quiz.validAccessories': 'Valid on any Link TI accessory',
    'quiz.printScreen': '📱 Take a screenshot of this screen and present it at our reception',
    'quiz.dontGiveUp': 'Don\'t give up! With more practice you will master the iPhone in no time.',
    'quiz.retakeQuiz': 'Retake Quiz',
    'quiz.shareResult': 'Share Result',
    'quiz.shareText': 'I just took the Link TI iPhone Quiz and got {score} out of {total} questions right ({percentage}%)! 📱✨',
    'quiz.copiedToClipboard': 'Result copied to clipboard!',
    
    // Service Details
    'serviceDetail.whatsappMessage': 'Hello, I would like to request a quote for repair.',
    'serviceDetail.ourServices': 'Our Services',
    'serviceDetail.completeSolutions': 'Complete solutions for your Apple device',
    'serviceDetail.commonProblems': 'Common Problems',
    'serviceDetail.frequentProblems': 'The most frequent problems we solve',
    'serviceDetail.getQuote': 'Get Quote',
    'serviceDetail.whatsappQuote': 'Quote via WhatsApp',
    'serviceDetail.requestRepair': 'Request Repair',
    'serviceDetail.needRepair': 'Need repair for your device?',
    'serviceDetail.contactToday': 'Contact us today for a no-obligation quote. Our specialists are ready to help.',
    'serviceDetail.contactUs': 'Contact Us',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'re here to help with your Apple devices',
    'contact.form.title': 'Send a Message',
    'contact.form.description': 'Need technical assistance for your Apple device? Contact us through one of our service channels.',
    'contact.form.success': 'Message sent successfully!',
    'contact.form.error': 'Error sending message. Please try again.',
    'contact.info.title': 'Contact Information',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekdays': 'Monday to Friday: 8am to 6pm',
    'contact.hours.saturday': 'Saturday: 8am to 12pm',
    'contact.hours.sunday': 'Sunday: Closed',
    
    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to the most common questions',
    'faq.seo.title': 'FAQ - Apple Technical Support',
    'faq.seo.description': 'Find answers to frequently asked questions about Apple device repair services.',
    'faq.errorLoading': 'Error loading frequently asked questions. Please try again later.',
    'faq.tryAgain': 'Try again',
    'faq.categories.services': 'Services',
    'faq.categories.scheduling': 'Scheduling',
    'faq.categories.timeframe': 'Timeframes',
    'faq.categories.warranty': 'Warranty',
    'faq.categories.procedures': 'Procedures',
    'faq.categories.general': 'General',
    'faq.default.services.question': 'What services do we offer?',
    'faq.default.services.answer': 'We offer specialized technical assistance services for Apple products, including iPhone, iPad, MacBook and Apple Watch. Our services include screen replacement, battery replacement, logic board repair, data recovery, among others.',
    'faq.default.scheduling.question': 'How to schedule a repair?',
    'faq.default.scheduling.answer': 'To schedule a repair, you can contact us via WhatsApp, phone, or through our appointment page. Just inform the device model and the problem you are facing, and our team will contact you to confirm the time and provide instructions.',
    'faq.default.timeframe.question': 'How long does it take to fix my device?',
    'faq.default.timeframe.answer': 'Repair time varies according to the type of service. Simple repairs like screen or battery replacement can be done the same day, while more complex repairs like logic board problems can take 2 to 5 business days, depending on parts availability.',
    'faq.default.warranty.question': 'Do repairs have warranty?',
    'faq.default.warranty.answer': 'Yes, all our services have warranty. Parts like batteries and screens have 90-day warranty, while logic board repairs generally have 30-day warranty. Specific terms are informed at the time of repaired device delivery.',
    'faq.default.data.question': 'Do I lose my data during repair?',
    'faq.default.data.answer': 'We do our best to preserve your data during repair, but we always recommend making a complete backup of your device before sending it for maintenance. In some specific cases, such as system formatting or logic board replacement, data loss is inevitable.',
    'faq.searchPlaceholder': 'Search question...',
    'faq.noResults': 'No questions found',
    'faq.stillHaveQuestions': 'Still have questions?',
    'faq.contactUs': 'Contact us',
    
    // Appointment Page
    'appointment.title': 'Appointment',
    'appointment.subtitle': 'Schedule your service quickly and easily',
    'appointment.form.title': 'Schedule Service',
    'appointment.form.success': 'Appointment scheduled successfully!',
    'appointment.form.error': 'Error scheduling appointment. Please try again.',
    'appointment.selectDate': 'Select date',
    'appointment.selectTime': 'Select time',
    'appointment.availableTimes': 'Available times',
    'appointment.noAvailableTimes': 'No available times for this date',
    'appointment.introduction': 'Here you can schedule your service directly with Apple or contact us via WhatsApp for more personalized service.',
    'appointment.buttonText': 'Schedule with Apple',
    'appointment.whatsappMessage': 'Hello, I would like to schedule a service for my Apple device.',
    'appointment.whatsappButton': 'Schedule via WhatsApp',
    'appointment.prepareSection.title': 'Prepare Your Device',
    'appointment.prepareSection.cards.backup.title': 'Make Backup',
    'appointment.prepareSection.cards.backup.description': 'Learn how to backup your data before repair.',
    'appointment.prepareSection.cards.prepare.title': 'Prepare for Repair',
    'appointment.prepareSection.cards.prepare.description': 'Important steps to prepare your device.',
    'appointment.prepareSection.cards.erase.title': 'Erase Data',
    'appointment.prepareSection.cards.erase.description': 'How to safely erase data before repair.',
    'appointment.viewGuide': 'View Guide',
    'appointment.checklist.title': 'Checklist',
    'appointment.checklist.items.backup': 'Make complete data backup',
    'appointment.checklist.items.findMy': 'Turn off "Find My iPhone/iPad"',
    'appointment.checklist.items.accessories': 'Remove cases and accessories',
    'appointment.checklist.items.case': 'Bring original box (if available)',
    'appointment.checklist.items.passwords': 'Write down important passwords',
    'appointment.seo.title': 'Appointment - Apple Technical Support',
    'appointment.seo.description': 'Schedule your Apple device repair service quickly and easily.',
    
    // Prices Page
    'prices.title': 'Price List',
    'prices.subtitle': 'Transparent pricing for all our services',
    'prices.filterByDevice': 'Filter by device',
    'prices.allDevices': 'All devices',
    'prices.service': 'Service',
    'prices.price': 'Price',
    'prices.warranty': 'Warranty',
    'prices.estimate': 'Estimate',
    'prices.contactForQuote': 'Contact for quote',
    'prices.note': 'Prices may vary depending on model and repair complexity.',
    'prices.searchPlaceholder': 'Search service...',
    'prices.dataNotSynced': 'Data not synced with Google Sheets.',
    
    // iPhone Service Page
    'iphone.title': 'iPhone Repair',
    'iphone.subtitle': 'Specialized services for all iPhone models',
    'iphone.description': 'We offer complete repair services for all iPhone models, from iPhone SE to the latest models. Our certified technicians use original Apple parts to ensure your device works like new.',
    'iphone.features.screenReplacement.title': 'Screen Replacement',
    'iphone.features.screenReplacement.description': 'Replacement of broken or defective screens using original Apple parts to maintain original quality and functionality.',
    'iphone.features.batteryReplacement.title': 'Battery Replacement',
    'iphone.features.batteryReplacement.description': 'Replacement of worn batteries that no longer hold charge, using original batteries for maximum duration.',
    'iphone.features.cameraRepair.title': 'Camera Repair',
    'iphone.features.cameraRepair.description': 'Repair of defective cameras, focus problems or that do not turn on, restoring complete photographic function.',
    'iphone.features.audioProblems.title': 'Audio Problems',
    'iphone.features.audioProblems.description': 'Repair of speakers, microphones and audio receivers for calls and quality media playback.',
    'iphone.features.boardRepair.title': 'Board Repair',
    'iphone.features.boardRepair.description': 'Diagnosis and repair of iPhone logic board problems, including connectivity and power issues.',
    'iphone.features.softwareUpdate.title': 'Software Update',
    'iphone.features.softwareUpdate.description': 'Resolution of software problems, system updates and restoration of frozen or faulty devices.',
    'iphone.problems.brokenScreen': 'Broken or cracked screen',
    'iphone.problems.batteryIssues': 'Battery does not charge or lasts little',
    'iphone.problems.wontTurnOn': 'iPhone does not turn on or restarts by itself',
    'iphone.problems.connectivity': 'Wi-Fi or cellular connectivity problems',
    'iphone.problems.camera': 'Camera does not work or has reduced quality',
    'iphone.problems.buttons': 'Physical buttons do not respond',
    'iphone.problems.charging': 'iPhone does not charge or does not recognize charger',
    'iphone.problems.audio': 'Speakers or microphone defective',
    'iphone.whatsappMessage': 'Hello, I would like to request a quote for iPhone repair.',

    // iPad Service Page
    'ipad.title': 'iPad Repair',
    'ipad.subtitle': 'Specialized services for the entire iPad line',
    'ipad.description': 'Our service center offers complete repairs for all iPad models, including iPad Pro, iPad Air, iPad mini and traditional iPad. We use original parts and certified technicians to ensure high quality repairs.',
    'ipad.features.screenReplacement.title': 'Screen Replacement',
    'ipad.features.screenReplacement.description': 'Repair of broken, cracked or touch-problematic screens using original parts for all iPad models.',
    'ipad.features.batteryReplacement.title': 'Battery Replacement',
    'ipad.features.batteryReplacement.description': 'Replacement of worn or charging-problematic batteries, restoring your iPad\'s original autonomy.',
    'ipad.features.connectorRepair.title': 'Connector Repair',
    'ipad.features.connectorRepair.description': 'Repair of damaged or poor-contact charging connectors, ensuring adequate charging.',
    'ipad.features.wifiProblems.title': 'Wi-Fi Problems',
    'ipad.features.wifiProblems.description': 'Diagnosis and repair of Wi-Fi and Bluetooth connectivity problems that affect iPad performance.',
    'ipad.features.buttonRepair.title': 'Button Repair',
    'ipad.features.buttonRepair.description': 'Repair of physical buttons like Power, Home and volume controls that do not respond correctly.',
    'ipad.features.softwareProblems.title': 'Software Problems',
    'ipad.features.softwareProblems.description': 'Resolution of crashes, slowness and other software problems through specialized diagnosis.',
    'ipad.problems.brokenScreen': 'Broken screen or touch problems',
    'ipad.problems.wontTurnOn': 'iPad does not turn on or turns off by itself',
    'ipad.problems.batteryDrain': 'Battery drains quickly',
    'ipad.problems.charging': 'Charging problems',
    'ipad.problems.connectivity': 'Wi-Fi or Bluetooth do not work properly',
    'ipad.problems.freezing': 'iPad freezing or slow performance',
    'ipad.problems.buttons': 'Physical buttons do not respond',
    'ipad.problems.camera': 'Problems with front or rear cameras',
    'ipad.whatsappMessage': 'Hello, I would like to request a quote for iPad repair.',

    // Mac Service Page
    'mac.title': 'Mac Repair',
    'mac.subtitle': 'Specialized services for MacBook, iMac and Mac mini',
    'mac.description': 'We offer complete repair and maintenance services for the entire Mac line, including MacBook Pro, MacBook Air, iMac and Mac mini. Our technicians specialize in diagnosing and solving complex hardware and software problems.',
    'mac.features.screenRepair.title': 'Screen Repair',
    'mac.features.screenRepair.description': 'Replacement of broken or display-problematic screens for MacBook Pro, MacBook Air and iMac.',
    'mac.features.ssdUpgrade.title': 'SSD/HD Upgrade',
    'mac.features.ssdUpgrade.description': 'Increased storage capacity and performance improvement with faster SSD installation.',
    'mac.features.ramUpgrade.title': 'RAM Upgrade',
    'mac.features.ramUpgrade.description': 'Increased RAM memory for better performance in multitasking and demanding applications.',
    'mac.features.logicBoardRepair.title': 'Logic Board Repair',
    'mac.features.logicBoardRepair.description': 'Diagnosis and repair of complex logic board problems that affect Mac operation.',
    'mac.features.batteryReplacement.title': 'Battery Replacement',
    'mac.features.batteryReplacement.description': 'Replacement of worn batteries in MacBooks, restoring original device autonomy.',
    'mac.features.keyboardRepair.title': 'Keyboard Repair',
    'mac.features.keyboardRepair.description': 'Repair of keyboards with defective keys, response problems or liquid damage.',
    'mac.problems.wontTurnOn': 'Mac does not turn on or shuts down unexpectedly',
    'mac.problems.brokenScreen': 'Broken screen or display problems',
    'mac.problems.battery': 'Battery does not charge or lasts little time',
    'mac.problems.slowPerformance': 'Slowness and performance problems',
    'mac.problems.keyboardTrackpad': 'Problems with keyboard or trackpad',
    'mac.problems.osErrors': 'Operating system errors',
    'mac.problems.strangeNoises': 'Strange noises (fan, hard drive)',
    'mac.problems.connectivity': 'Wi-Fi or Bluetooth connection problems',
    'mac.problems.liquidDamage': 'Liquid damage',
    'mac.whatsappMessage': 'Hello, I would like to request a quote for Mac repair.',

    // Apple Watch Service Page
    'watch.title': 'Apple Watch Repair',
    'watch.subtitle': 'Specialized services for all Apple Watch models',
    'watch.description': 'Our authorized center offers complete repairs for all Apple Watch models, from Series 1 to the latest models. We use original parts and certified technicians to ensure perfect operation of your device.',
    'watch.features.screenReplacement.title': 'Screen Replacement',
    'watch.features.screenReplacement.description': 'Repair of broken or scratched screens for all Apple Watch models, restoring original appearance.',
    'watch.features.batteryReplacement.title': 'Battery Replacement',
    'watch.features.batteryReplacement.description': 'Replacement of worn batteries that no longer hold charge, restoring your Apple Watch autonomy.',
    'watch.features.buttonRepair.title': 'Button Repair',
    'watch.features.buttonRepair.description': 'Repair of digital crown and side buttons that do not respond correctly to touch or pressure.',
    'watch.features.sensorProblems.title': 'Sensor Problems',
    'watch.features.sensorProblems.description': 'Diagnosis and repair of heart rate, accelerometer and other specific sensors.',
    'watch.features.sealReplacement.title': 'Seal Replacement',
    'watch.features.sealReplacement.description': 'Water resistance restoration with replacement of seals and protective gaskets.',
    'watch.features.softwareUpdate.title': 'Software Update',
    'watch.features.softwareUpdate.description': 'Resolution of software problems, system restoration and specific bug fixes.',
    'watch.problems.brokenScreen': 'Broken or scratched screen',
    'watch.problems.batteryDrain': 'Battery drains quickly',
    'watch.problems.wontTurnOn': 'Apple Watch does not turn on or charge',
    'watch.problems.buttons': 'Buttons do not respond correctly',
    'watch.problems.sensors': 'Health sensors do not work properly',
    'watch.problems.pairing': 'iPhone pairing problems',
    'watch.problems.waterResistance': 'Loss of water resistance',
    'watch.problems.crashes': 'Crashes or unexpected restarts',
    'watch.whatsappMessage': 'Hello, I would like to request a quote for Apple Watch repair.',

    // AirPods Service Page
    'airpods.title': 'AirPods Repair',
    'airpods.subtitle': 'Specialized services for all AirPods models',
    'airpods.description': 'We offer complete repairs for all AirPods models, including AirPods Pro, AirPods Max and traditional AirPods. Our specialized technicians use precision equipment to ensure high quality repairs.',
    'airpods.features.batteryReplacement.title': 'Battery Replacement',
    'airpods.features.batteryReplacement.description': 'Replacement of worn batteries that no longer hold adequate charge in AirPods.',
    'airpods.features.connectivityRepair.title': 'Connectivity Repair',
    'airpods.features.connectivityRepair.description': 'Solution for pairing and Bluetooth connection problems with Apple devices.',
    'airpods.features.deepCleaning.title': 'Deep Cleaning',
    'airpods.features.deepCleaning.description': 'Internal and external specialized cleaning to remove dirt and improve audio quality.',
    'airpods.features.audioCalibration.title': 'Audio Calibration',
    'airpods.features.audioCalibration.description': 'Adjustment and calibration of audio drivers to restore original sound quality.',
    'airpods.features.chargingCaseRepair.title': 'Charging Case Repair',
    'airpods.features.chargingCaseRepair.description': 'Repair of charging case, including charging problems and connectors.',
    'airpods.features.microphoneProblems.title': 'Microphone Problems',
    'airpods.features.microphoneProblems.description': 'Diagnosis and repair of microphone problems that affect calls and voice commands.',
    'airpods.problems.batteryIssues': 'Battery drains quickly',
    'airpods.problems.pairing': 'AirPods do not pair with devices',
    'airpods.problems.audioQuality': 'Reduced or distorted audio quality',
    'airpods.problems.caseNotCharging': 'Case does not charge AirPods',
    'airpods.problems.microphone': 'Microphone problems in calls',
    'airpods.problems.notRecognized': 'AirPods not recognized by iPhone',
    'airpods.problems.audioNoise': 'Noise or static during playback',
    'airpods.problems.noiseCancellation': 'Problems with noise cancellation (AirPods Pro)',
    'airpods.whatsappMessage': 'Hello, I would like to request a quote for AirPods repair.',

    // Other Services Page
    'otherServices.title': 'Other Services',
    'otherServices.subtitle': 'Specialized services for all your Apple devices',
    'otherServices.description': 'In addition to traditional repairs, we offer a complete range of services to keep your Apple devices working perfectly.',
    'otherServices.beats.title': 'Beats',
    'otherServices.beats.description': 'Complete services for Beats headphones, including driver repair, pad replacement, cable problems and general maintenance.',
    'otherServices.beats.driverRepair': 'Driver repair',
    'otherServices.beats.padReplacement': 'Pad replacement',
    'otherServices.beats.cableRepair': 'Cable repair',
    'otherServices.beats.preventiveMaintenance': 'Preventive maintenance',
    'otherServices.beats.whatsappMessage': 'Hello, I would like information about Beats headphone repair.',
    'otherServices.beats.getQuote': 'Quote for Beats',
    'otherServices.rental.title': 'Rental',
    'otherServices.rental.description': 'Temporary smartphone rental for use during your device repair period, keeping you always connected.',
    'otherServices.rental.temporaryIphone': 'Temporary iPhone',
    'otherServices.rental.dailyWeekly': 'Daily or weekly rental',
    'otherServices.rental.basicPremium': 'Basic and premium models',
    'otherServices.rental.setupIncluded': 'Setup included',
    'otherServices.rental.whatsappMessage': 'Hello, I would like information about smartphone rental.',
    'otherServices.rental.requestRental': 'Request Rental',
    'otherServices.recovery.title': 'Recovery',
    'otherServices.recovery.description': 'Specialized services in lost data recovery, complete backup and restoration of important information from your devices.',
    'otherServices.recovery.photosVideos': 'Photo and video recovery',
    'otherServices.recovery.fullBackup': 'Complete backup',
    'otherServices.recovery.contactRestore': 'Contact restoration',
    'otherServices.recovery.dataMigration': 'Data migration',
    'otherServices.recovery.whatsappMessage': 'Hello, I would like information about data recovery.',
    'otherServices.recovery.recoverData': 'Recover Data',
    'otherServices.priceTable.title': 'Price Table - Special Services',
    'otherServices.priceTable.description': 'Check our price table for specialized services. Prices subject to change upon evaluation.',
    'otherServices.categories.physicalCleaning': 'Physical Cleaning',
    'otherServices.categories.backupRestore': 'Backup and Restoration',
    'otherServices.categories.smartphoneRental': 'Smartphone Rental',
    'otherServices.categories.diagnosticConsulting': 'Diagnostic and Consulting',
    'otherServices.cleaning.iphone': 'Complete internal and external cleaning',
    'otherServices.cleaning.ipad': 'Complete internal and external cleaning',
    'otherServices.cleaning.macbook': 'Internal and external cleaning, keyboard and screen',
    'otherServices.cleaning.imac': 'Complete internal and external cleaning',
    'otherServices.cleaning.applewatch': 'External cleaning and band',
    'otherServices.backup.iphoneipad': 'Complete backup and data restoration',
    'otherServices.backup.mac': 'Time Machine or custom backup',
    'otherServices.backup.dataRecovery': 'Lost file recovery',
    'otherServices.rental.temporaryIphoneDaily': 'iPhone rental during your device repair',
    'otherServices.rental.basicIphone': 'Weekly iPhone rental with basic features',
    'otherServices.rental.premiumIphone': 'Weekly iPhone rental with all features',
    'otherServices.diagnostic.complete': 'Detailed device analysis',
    'otherServices.diagnostic.technicalConsulting': 'Specialized technical guidance',
    'otherServices.diagnostic.initialSetup': 'Initial setup of new devices',
    'otherServices.table.device': 'Device/Service',
    'otherServices.table.price': 'Price',
    'otherServices.table.description': 'Description',
    'otherServices.note': 'All prices are estimates and may vary according to repair complexity. We offer free quotes with no obligation. 90-day warranty for all services.',
    'otherServices.customService.title': 'Need a custom service?',
    'otherServices.customService.description': 'Contact us for unlisted services or custom quotes.',
    'otherServices.customService.whatsappMessage': 'Hello, I would like information about specialized services.',

    // SOS Dados Page
    'sosData.badge': 'EMERGENCY',
    'sosData.hero.title': 'SOS Data',
    'sosData.hero.description': 'Lost important data? We can help you recover it!',
    'sosData.hero.button': 'Recover My Data',
    'sosData.hero.diagnosisButton': 'Free Diagnosis',
    'sosData.hero.clients': 'Over 1000 customers served',
    'sosData.whatsappMessage': 'Hello, I need emergency data recovery for my device.',
    'sosData.alert.message': '⚠️ The sooner you contact us, the greater the chances of recovery - Do not turn on the device!',
    'sosData.servicesSection.title': 'What Can We Recover?',
    'sosData.servicesSection.description': 'We specialize in data recovery from different types of devices and storage media.',
    'sosData.services.hdd.title': 'Hard Drives & SSDs',
    'sosData.services.hdd.description': 'Recovery from mechanical damage, logical corruption, and system failures.',
    'sosData.services.mobile.title': 'Mobile Devices',
    'sosData.services.mobile.description': 'iPhone, iPad and Android with physical damage or system corruption.',
    'sosData.services.computers.title': 'Computers',
    'sosData.services.computers.description': 'Mac, PC, laptops with system problems or hardware failures.',
    'sosData.services.servers.title': 'Servers & RAID',
    'sosData.services.servers.description': 'Critical data recovery from corporate servers and RAID systems.',
    'sosData.urgency.critical': 'Critical',
    'sosData.urgency.high': 'High',
    'sosData.urgency.medium': 'Medium',
    'sosData.processSection.title': 'Our Recovery Process',
    'sosData.processSection.description': 'A safe and professional process to maximize your chances of recovery.',
    'sosData.steps.contact.title': 'Emergency Contact',
    'sosData.steps.contact.description': 'Contact us immediately and describe the problem.',
    'sosData.steps.diagnosis.title': 'Free Diagnosis',
    'sosData.steps.diagnosis.description': 'Complete analysis to assess recovery possibilities.',
    'sosData.steps.quote.title': 'Quote Approval',
    'sosData.steps.quote.description': 'We present a detailed budget with no surprises.',
    'sosData.steps.recovery.title': 'Data Recovery',
    'sosData.steps.recovery.description': 'We use advanced techniques to recover your files.',
    'sosData.steps.delivery.title': 'Secure Delivery',
    'sosData.steps.delivery.description': 'Your data is returned safely and confidentially.',
    'sosData.featuresSection.title': 'Why Choose Us?',
    'sosData.features.security.title': 'Total Security',
    'sosData.features.security.description': 'Complete confidentiality and secure handling of your data.',
    'sosData.features.diagnosis.title': 'Free Diagnosis',
    'sosData.features.diagnosis.description': 'Complete evaluation at no cost and with no commitment.',
    'sosData.features.successRate.title': '98% Success Rate',
    'sosData.features.successRate.description': 'High recovery success rate with advanced technology.',
    'sosData.features.equipment.title': 'Advanced Equipment',
    'sosData.features.equipment.description': 'Clean room and cutting-edge technology for complex cases.',
    'sosData.cta.title': 'Every Second Counts!',
    'sosData.cta.description': 'The sooner you contact us, the greater the chances of complete recovery of your data.',
    'sosData.cta.whatsapp': 'Emergency WhatsApp',
    'sosData.cta.features.diagnosis': 'Free Diagnosis',
    'sosData.cta.features.noDataNoPayment': 'No Data, No Payment',
    'sosData.cta.features.technology': 'Advanced Technology',
    
    // Footer
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookie Policy',
    'footer.warranty': 'Warranty',
    
    // Error Messages
    'error.pageNotFound': 'Page not found',
    'error.goHome': 'Go home',
    'error.somethingWrong': 'Something went wrong',
    'error.tryAgain': 'Try again',
    
    // Course Pages
    'course.title': 'iPhone Course',
    'course.subtitle': 'Learn to use your iPhone like a professional',
    'course.beginner': 'Beginner',
    'course.intermediate': 'Intermediate',
    'course.advanced': 'Advanced',
    'course.contents': 'Contents',
    'course.quiz': 'Quiz',
    'course.progress': 'Progress',
    'course.completed': 'Completed',
    'course.inProgress': 'In Progress',
    'course.notStarted': 'Not Started'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
